### ISSUE TITLE
the aside tag is used like the nav tag and shouldnt be used like an unordered list

### ISSUE THREAD

**Issue by PKCRY** [Vanillan-MellonDrop/Vanillan-Mellondrop.github.io#1]
https://github.com/Vanillan-MellonDrop/Vanillan-Mellondrop.github.io/blob/85fed12dc5e7798ad83ea7641a68805397ff0791/My-Contact-Info.html#L17

**Comment by PKCRY** [comment]
don't use breaktags for style purposes. Use css

**Comment by Vanillan-MellonDrop** [comment]
I fixed the asides, but I used the break tags to create a new line. I have something attached to the paragraph, so I don't want to close the paragraph just to get things on a new line.

**Comment by Vanillan-MellonDrop** [comment]
I could shift things to a div, but if I update it, I take that away from someone else getting their Hacktober Fest points.

**Comment by PKCRY** [comment]
but breaks are not supposed to be used for html. if you use display block or an unordered list for the html then it will do that on its own

**Comment by zachfedor** [comment]
@PKCRY is right, we shouldn't be using `<br>` tags for styling purposes. If you want the `<a>` elements on separate lines, then it would be more correct to use what we learned in CSS. By default, anchors are `display: inline;` so they're all on the same line. Change this property to get them on separate lines.
