### ISSUE TITLE
Too many stylesheets.

### ISSUE THREAD

**Issue by kainguyen123-oss** [Vanillan-MellonDrop/Vanillan-Mellondrop.github.io#2]
There's a lot of stylesheets, i think we could put it all on one page.

**Comment by zachfedor** [comment]
@thienqui-communistspy is correct. You could reduce a lot of the duplicated work if you stuck to one stylesheet. It's usually best practice to have a single stylesheet for an entire website, regardless of the number of HTML files, so that all the HTML files can benefit from the same styles.
